[package]
name = "zoomrs"
version = "0.1.0"
authors = ["Daniele Fongo & Paolo D'Incau"]
edition = "2018"

[dependencies]
thiserror = "1.0.25"

[dev-dependencies]
claim = "0.5.0"
cappuccino = { git = "https://github.com/danielefongo/cappuccino", branch = "main" }